CREATE OR REPLACE PACKAGE PAYMENT_PROCESSING_PKG AS

    PROCEDURE PROCESS_PENDING_PAYMENTS;

    PROCEDURE LOG_PROCESSING_ERROR(
        P_PAYMENT_ID IN PAYMENTS.ID%TYPE,
        P_ERROR_MESSAGE IN VARCHAR2
    );

END PAYMENT_PROCESSING_PKG;
/

CREATE OR REPLACE PACKAGE BODY PAYMENT_PROCESSING_PKG AS

    PROCEDURE LOG_PROCESSING_ERROR(
        P_PAYMENT_ID IN PAYMENTS.ID%TYPE,
        P_ERROR_MESSAGE IN VARCHAR2
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO PAYMENT_PROCESS_LOG (PAYMENT_ID, ERROR_MESSAGE, ERROR_DATE)
        VALUES (P_PAYMENT_ID, SUBSTR(P_ERROR_MESSAGE, 1, 4000), SYSTIMESTAMP);

        COMMIT;
    END LOG_PROCESSING_ERROR;

    PROCEDURE PROCESS_PENDING_PAYMENTS IS
    BEGIN
        FOR PAYMENT_RECORD IN (
            SELECT ID
            FROM PAYMENTS
            WHERE STATUS = 'PENDING'
            FOR UPDATE SKIP LOCKED
        ) LOOP
            BEGIN
                UPDATE PAYMENTS
                SET STATUS = 'PROCESSED'
                WHERE ID = PAYMENT_RECORD.ID;
            EXCEPTION
                WHEN OTHERS THEN
                    LOG_PROCESSING_ERROR(PAYMENT_RECORD.ID, SQLERRM);
            END;
        END LOOP;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            LOG_PROCESSING_ERROR(NULL, SQLERRM);
            RAISE;
    END PROCESS_PENDING_PAYMENTS;

END PAYMENT_PROCESSING_PKG;
/
