SELECT
    C.ID AS CUSTOMER_ID,
    C.NAME AS CUSTOMER_NAME,
    C.COUNTRY,
    SUM(P.AMOUNT) AS TOTAL_AMOUNT_PAID,
    COUNT(P.ID) AS PAYMENT_COUNT,
    AVG(P.AMOUNT) AS AVERAGE_TICKET
FROM CUSTOMERS C
JOIN PAYMENTS P ON P.CUSTOMER_ID = C.ID
WHERE P.CREATED_AT >= (SYSDATE - 30)
GROUP BY C.ID, C.NAME, C.COUNTRY
ORDER BY TOTAL_AMOUNT_PAID DESC
FETCH FIRST 10 ROWS ONLY;
